In [1]:
import torch

In [4]:
scalar = torch.tensor(8)

In [5]:
vector = torch.tensor([7,7])

In [7]:
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [13]:
float_32_tensor = torch.tensor([1.0,2.0,3.0])

In [14]:
float_32_tensor.dtype

torch.float32

In [16]:
float_64_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float64)
float_64_tensor.dtype

torch.float64

In [17]:
tensor1 = torch.tensor([1,2])

In [18]:
tensor1.device

device(type='cpu')

In [19]:
tensor2 = torch.tensor([1,2,3],device='cuda:0')

In [20]:
tensor2.device

device(type='cuda', index=0)

In [23]:
s1 = torch.tensor([[1,2,3],[2,3,4]])

In [24]:
s2 = torch.tensor([[3,4,5],[6,7,8]])

In [25]:
s1 + s2

tensor([[ 4,  6,  8],
        [ 8, 10, 12]])

In [26]:
s1 * s2

tensor([[ 3,  8, 15],
        [12, 21, 32]])

In [28]:
s3 = torch.tensor(1)

In [29]:
s4 = torch.tensor(2)

In [30]:
s1+s4

tensor([[3, 4, 5],
        [4, 5, 6]])

In [31]:
y_reshaped.shape

NameError: name 'y_reshaped' is not defined

In [33]:
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
import numpy as np

In [39]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [36]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])